### PR TITLE
Made multiple improvements and changes to passwordManager

### PR DESCRIPTION
**Pull request by prithvidiamond1**
The improvements I have made are as follows:
- Shifted from using `random` module to `secrets`. This is in fact mandated by Python themselves as can be found as a warning in the documentation for the `random` module [here](https://docs.python.org/3/library/random.html). 
- Incorporated the use of the `string` module to make the code look cleaner by reducing visibility of verbosely typed template strings (namely `lower`, `upper` and `digits`).
- Made changes to password generating sections of code (under function `low()`) by writing a new function `sample()` (that is similar to `random.sample()` but using the `secrets` module) to reduce repetition of code which makes code more readable and more concise.
- Reduced dependence on external modules such as `pyperclip` for functions that can be performed using built-in modules as this improves user experience.
- Removed bits of useless code that serve no real purpose.

Functionally the program is the same but the changes under the hood ensure better readability of the code,  better user experience for people wanting to try out the program and is technically more secure than before!

I also have a few improvements that I suggest you and the other contributors to add (and of course I am also willing to do some of the work required for this):
- There is no real difference in security between Low and Medium modes (one generates a purely lowercase string of characters and the other a purely uppercase string of characters) and the strength of such a password is quite low. This can be easily rectified by adding numbers as well as uppercase and lowercase characters into the mix. So Low mode would be lowercase characters only, Medium mode would be lowercase, uppercase and numeric characters and Strong can stay as is with lowercase, uppercase, numeric and punctuation characters (although I suggest you use the full list of punctuations present under `secrets.punctuation` as that would enhance the strength of the passwords generated even more!)
- Add ability to clear all stored passwords. Of course do add this with a confirmation dialogue box! You don't want people accidently deleting all their saved passwords!)
- Improve readability further by giving more descriptive names to variables and functions. Names like `low()` for a function that actually generates passwords, is not very descriptive and this decreases readability of the code.
- Aesthetics of the program window can be improved or at least made a bit more uniform.
- Add a password protection system for the saved passwords. As is the program isn't a very secure password manager.
- (This maybe a bit difficult but if we can pull it off, it would really complete the entire program!) Store the passwords with decent encryption.

Now you maybe wondering? Why would anybody contribute so much to a project free of cost?

Well I found your repository (it is a very nice repository) due to Hacktoberfest 2020 and who doesn't love contributing to open-source software? Also I am yet to see through all the other stuff on this repository!

I hope you do appreciate the time and effort that has gone into this contribution and will accept this pull request! (Also when you do, do so with the `hacktoberfest-accepted` tag!)

If you have any comments to add or any queries, do reach out to me! Also feel free to put through your complaints! (Although hope there are none!)

### CODE REVIEW

**Comment by prithvidiamond1** [comment]
@Aniket762 can you please review this pull request and if it is a good contribution merge it into your master branch. Thank you!

**Comment by Aniket762** [comment]
Thanks !

**Comment by prithvidiamond1** [comment]
@Aniket762 No problem! I really like your repository! I look forward to exploring the rest of the repository and making many more meaningful and high quality contributions!

**Comment by Aniket762** [comment]
> @Aniket762 No problem! I really like your repository! I look forward to exploring the rest of the repository and making many more meaningful and high quality contributions!

Thanks!

 You can directly contribute to (https://github.com/sumana2001/python) from where I forked it and you can also contribute in  (https://github.com/Webwiznitr) repo we have a lot of beginner issues 

Happy Coding 😁

**Comment by prithvidiamond1** [comment]
Sure, thanks for letting me know!

**Pull request merged**
